name: Build test source on linux 
on: [push]
jobs:
  build-source-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build source
        run: |
          make all -c ./fileio
          echo "Done"
